Repository ember-cli/ember-cli-htmlbars-inline-precompile, pull requests merged in 2018-10, with the labels that each got.

#116 Pin subdependencies to versions using sane@2
  package.json
  yarn.lock
Labels: internal

#115 Update `ember-cli-babel` peer dependency to support Babel 7 too
  package.json
Labels: enhancement

#117 Use `lerna-changelog` to generate `CHANGELOG.md`
  CHANGELOG.md
  package.json
  yarn.lock
Labels: documentation

#118 Update `.npmignore` file
  .npmignore
Labels: enhancement

#119 Drop Node.js 4 support
  .travis.yml
  package.json
Labels: breaking

#126 Remove Bower and run node-tests in CI
  .bowerrc
  .npmignore
  .travis.yml
  bower.json
  config/ember-try.js
  index.js
  node-tests/test.js
  package.json
  tests/dummy/config/environment.js
  tests/dummy/config/optional-features.json
  tests/test-helper.js
  yarn.lock
Labels: breaking

#120 Upgrading ember-cli
  .eslintignore
  .eslintrc.js
  .gitignore
  .npmignore
  .template-lintrc.js
  .travis.yml
  LICENSE.md
  ember-cli-build.js
  package.json
  testem.js
  tests/dummy/app/app.js
  tests/dummy/app/components/comment-redact.js
  tests/dummy/app/components/days-ago.js
  tests/dummy/app/components/inline-precompilation.js
  tests/dummy/app/components/multiline-string.js
  tests/dummy/app/components/string-parameter.js
  tests/dummy/app/index.html
  tests/dummy/app/router.js
  tests/dummy/app/templates/application.hbs
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/dummy/public/crossdomain.xml
  tests/helpers/.gitkeep
  tests/helpers/destroy-app.js
  tests/helpers/module-for-acceptance.js
  tests/helpers/resolver.js
  tests/helpers/start-app.js
  tests/unit/components/coffeescript-support-test.coffee
  tests/unit/components/comment-redact-test.js
  tests/unit/components/days-ago-test.js
  tests/unit/components/inline-precompilation-test.js
  tests/unit/components/multiline-string-test.js
  tests/unit/components/string-parameter-test.js
  yarn.lock
Labels: breaking
